from tkinter import *
app = Tk()
app.title("EMAIl MODIFIER")
l1 = Label(app,text="Welcome To Email Modifier")
l1.pack()
l2 = Label(app,text="Enter Your Email Example - Ritik@example.com \n You can change suffix and domain")
l2.pack()
mail = Entry(app,text="")
mail.pack()
def modifier():
    email = mail.get()
    index = email.index("@")
    l3.config(text=(email[0:index]))
def changedomain():
    email = mail.get()
    index = email.index("@")
    l4= Label(app,text="Enter New domain Ex - @example.com")
    l4.pack()
    change = Entry(app,text="")
    change.pack()
    def changedomainfinal():
      newdomain = change.get()
      l5.config(text=(email[0:index]+str(newdomain)+" New Email!"))
    b3 = Button(app,text="Change domain",command=changedomainfinal)
    b3.pack()
      
b1 = Button(app,text="Get Username",command=modifier)
b1.pack()
b2 = Button(app,text="Change domain",command=changedomain)
b2.pack()
l3 = Label(app,text="")
l3.pack()
l5 = Label(app,text="")
l5.pack()
app.mainloop()